### ISSUE TITLE
Macedonia

### ISSUE THREAD

**Issue by Tridson** [Akaflieg-Freiburg/enrouteServer#22]
Hi,
I am a pilot from North Macedonia and I think that it would be very useful to have this tool available on the phone/tablet in flight as a back up to the Garmin GPS. I looked up at the openAIP maps and everything seems to match up to the official aviation maps.

**Comment by kebekus** [comment]
Dear Tridson,

thank you for your mail. I would be happy to add maps for Macedonia, but I am unsure about the openAIP status. As far as I can see, openAIP does not have any airspace information about Macedonia. For instance, I cannot see the control zone around Skopje on http://maps.openaip.net

Please correct me if I am wrong here and if I am missing something. 

Best

Stefan.

**Comment by Tridson** [comment]
You are correct, it is missing the CTR at LWSK and the restricted zone over the city. It also misses airspace information about Ohrid LWOH. But it could be very useful if we could have this as a back up. I hope openAIP updates their aviation maps for our country so it includes these things.
Kind regards.

**Comment by kebekus** [comment]
Dear Tridson,

ok, we're on the same page here. Since I want the app to be known as reliable and complete, I have the policy to include a country only when all the data is there. Thus, I have to ask for your understanding that I will not add Macedonia at this point. I will hence close the issue now.

>  I hope openAIP updates their aviation maps for our country so it includes these things. 

Like **Enroute Flight Navigation**, openAIP is a volunteer effort. Aviation data for Macedonia will only be added to openAIP if someone from your country volunteers to provide the data and to maintain it. Let me know if you are interested to do the job, I could then get you in touch with the relevant people there.

Best,

Stefan.

**Comment by Tridson** [comment]
Hello,
Okay hook me up to the people there and I will give it a healthy attempt.
Kind regards.

**Comment by kebekus** [comment]
Will do.

**Comment by kebekus** [comment]
Sorry for the delay … my workload is pretty intense. Can you send me your full name and e-mail address via some channel, so I can introduce you?

**Comment by kebekus** [comment]
Dear Tridson,

did you get my last message? To introduce you, it would be great if I had your e-mail address. Thanks!

Best,

Stefan.
