### ISSUE TITLE
Brazil maps waypoints update

### ISSUE THREAD

**Issue by gustavovicenti** [Akaflieg-Freiburg/enrouteServer#24]
BRAZIL - Navigation maps and airfields are out of date. In May/20 there was a big update in all Brazilian airspace. In Brazil map,  waypoint list is also missing.
I would like to contribute and update maps, waypoints and airfields. I have updated data and maps.

[waypoint_aisweb.xlsx](https://github.com/Akaflieg-Freiburg/enroute/files/7333874/waypoint_aisweb.xlsx)

[REA Sao Paulo 2021 05.pdf](https://github.com/Akaflieg-Freiburg/enroute/files/7333880/REA.Sao.Paulo.2021.05.pdf)

[REA Vale do Paraiba 2021 05.pdf](https://github.com/Akaflieg-Freiburg/enroute/files/7333883/REA.Vale.do.Paraiba.2021.05.pdf)

[REA Rio de Janeiro 2021 05.pdf](https://github.com/Akaflieg-Freiburg/enroute/files/7333891/REA.Rio.de.Janeiro.2021.05.pdf)

[REA Natal 2021 05.pdf](https://github.com/Akaflieg-Freiburg/enroute/files/7333894/REA.Natal.2021.05.pdf)

[REA Recife 2021 04.pdf](https://github.com/Akaflieg-Freiburg/enroute/files/7333895/REA.Recife.2021.04.pdf)

[REA Manaus 2021 04.pdf](https://github.com/Akaflieg-Freiburg/enroute/files/7333896/REA.Manaus.2021.04.pdf)

[REA Florianopolis 2020 09.pdf](https://github.com/Akaflieg-Freiburg/enroute/files/7333897/REA.Florianopolis.2020.09.pdf)

[REA Fortaleza 2020 05.pdf](https://github.com/Akaflieg-Freiburg/enroute/files/7333899/REA.Fortaleza.2020.05.pdf)

[REA Ribeirao Preto 2020 04.pdf](https://github.com/Akaflieg-Freiburg/enroute/files/7333901/REA.Ribeirao.Preto.2020.04.pdf)

**Comment by kebekus** [comment]
Dear Gustavo,

thank you for your message -- and thank you for interest to help!

The app "Enroute Flight Navigation" takes the airspace data (and in fact all other data) from openAIP. This is a free, worldwide aviation database that is run by a group of volunteers, and the data is automatically used to generate the maps for "Enroute Flight Navigation". In order to correct the data, I recommend to contact people at openAIP. I am sure that the folks there will be glad for any help that they can get.

Here's what you can do.

- Go to the website [openAIP.net](https://openaip.net) and open an account. As soon as your account is verified, you can edit all waypoints and correct the data directly. Any corrections that you do will show up in Enroute automatically within a week. They are currently updating the website, so be prepared for some quirks.
- Even with an account, you cannot modify airspace data. For that, log into your account and turn to one of the forums. Better still, contact the relevant people directly by e-mail. I am usually in touch with Peter Kemme, who has kindly volunteered to help and who might direct you to the relevant people. You can find Peter's e-mail address in the Enroute app ("Menu/Error Report/Airspace/ …"). 

Let me know if you have difficulties to find Peter's address, and please let me know of any progress that you are making.

Best wishes from Germany,

Stefan.

**Comment by gustavovicenti** [comment]
Hi Stefan. Thanks.

As you told me, I created an account on openAIP and verified it. I couldn't
find a way to include waypoints and navaids. I have already opened a
request on the forum, as the title BRASIL UPDATE, but so far I have not
received any feedback.

For your information, in Brazil, the official aviation information is AISWEB
- Informações Aeronáuticas do Brasil (decea.mil.br)
<https://aisweb.decea.mil.br/>. So you can find all information about
airspaces, airways, navaids, waypoints.

About the app, if you would like to translate to Portuguese or Spanish, I
can help you with that. I'm a professional pilot at a regional airline.

Finally, I would like to suggest you the possibility of a DIRECT TO
function, maybe clicking on navaid or waypoint.

Thank you again. Best regards


*GUSTAVO VICENTE*

  TIM:   11-98515-5124

*  Skype: live:gustavo.vicenti*

*  ***@***.*** ***@***.***>*

**Comment by kebekus** [comment]
```
About the app, if you would like to translate to Portuguese or Spanish, I
can help you with that. I'm a professional pilot at a regional airline.
```

That would be highly welcome! For that, it would probably be easiest to communicate via e-mail. Can you send me a mail to stefan.kebekus@gmail.com ? -- Thanks!

Best,

Stefan.

**Comment by kebekus** [comment]
@gustavovicenti Dear Gustavo, this issue has been open for a while. Has there been any progress?

**Comment by kebekus** [comment]
Closed for loss of communication. Feel free to re-open if necessary.
